version: '3.4'

networks:
  dotnet6jwtassignmentapi-dev:
    driver: bridge 

services:
  dotnet6jwtassignmentapi:
    image: dotnet6jwtassignmentapi:latest
    depends_on:
      - "postgres_db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_db;port=5432;database=db_dotNET6JwtAssignment;username=postgres;password=123"
    networks:
      - dotnet6jwtassignmentapi-dev  
  
  postgres_db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "db_dotNET6JwtAssignment"
    networks:
      - dotnet6jwtassignmentapi-dev
volumes:
  db_volume:
         